### PR TITLE
Add Vale GH action

### PR DESCRIPTION
**Pull request by piraka9011**
Add the Vale GH action workflow.

Depends on:

* [x] #94 

Signed-off-by: Anas Abou Allaban <allabana@amazon.com>

### CODE REVIEW

**Comment by emersonknapp** [comment]
Except - the Vale action prints this 
```
Vale: Found 71 suggestion(s), 57 warning(s), and 20 error(s).
```
but doesn't go yellow or red, is this the intended behavior?

**Comment by piraka9011** [comment]
> ... doesn't go yellow or red, is this the intended behavior?

No, see the following [issue](https://github.com/errata-ai/vale-action/issues/6). It looks there's a fix in progress. Not sure how they got it working in their examples tho.

**Comment by emersonknapp** [comment]
Does this PR replace https://github.com/ros-tooling/cross_compile/pull/77 ? If so, can you close that one with a note?

**Comment by piraka9011** [comment]
Closing since the vale action doesn't seem to be working at the moment.

**Pull request closed without merging**
