### PR TITLE
Source /custom-data/setup.bash on sysroot build

### PR DESCRIPTION
**Pull request by hidmic**
Just a means to control the build environment. I do not have a strong opinion about how this is achieved (as long as there is a way). As such, I'm open to completely changing this patch if a more suitable alternative exists. 

Thanks for the tool BTW !

### CODE REVIEW

**Review by emersonknapp — APPROVED** [review]
LGTM - I've got no concerns with this

**Comment by hidmic** [comment]
Most jobs are failing because of unrelated reasons. I have to take a closer look at the `shellcheck` one though.

**Comment by hidmic** [comment]
Rebased to please workflows.

**Comment by TSC21** [comment]
Does this mean we can eventually use this to support workspace overlaying and so answer to https://github.com/ros-tooling/cross_compile/issues/299?

**Comment by emersonknapp** [comment]
It seems like you could mount an underlay workspace into the `custom-data-dir`, then source it in `custom-data/setup.bash` - so theoretically yes, though I haven't tried it. Would love to hear back if that works, and if so, an addition to the README explaining this workflow would be really useful.

**Pull request merged**
