### PR TITLE
First pass at specifying a custom docker image

### PR DESCRIPTION
**Pull request by kjeremy**
#285

### CODE REVIEW

**Comment by kjeremy** [comment]
Can I get some guidance on writing a test for this?

**Comment by emersonknapp** [comment]
This looks pretty good! note - we'll want an addition to the README as well once this is finalized.

> Can I get some guidance on writing a test for this?

Some simple unit testing around `Platform` would be good. There isn't (currently) a Python-based test that runs the full pipeline to try out the CLI entrypoint in that way - but the Github Action workflows call [run_e2e_test.sh](https://github.com/ros-tooling/cross_compile/blob/master/test/run_e2e_test.sh), you could add another test condition there to try out this with a base image. I might try using `rostooling/setup-ros-docker:ubuntu-focal-ros-foxy-ros-base-latest` as the override sysroot, for something that only needs dependencies from the `ros-base` set.

**Comment by kjeremy** [comment]
@emersonknapp

In my testing this doesn't seem to trigger a build. Do I need to somehow copy the build_workspace.sh file into the container?

**Comment by emersonknapp** [comment]
> In my testing this doesn't seem to trigger a build. Do I need to somehow copy the build_workspace.sh file into the container and execute it?

Oh - yes, I made a mistake suggesting that image as the sysroot. Given the way the build currently works, you'll probably need to match the setup from this line on https://github.com/ros-tooling/cross_compile/blob/master/ros_cross_compile/docker/sysroot.Dockerfile#L89

Thinking about it further, this feature is probably best suited (in the first version) to just reusing an image from a prior cross-compile build. Does that sound right to you? If so, then we could somehow specify or get the name of the sysroot image from a previous test build, and run using that.

**Comment by kjeremy** [comment]
That sounds reasonable. Ultimately I would like to be able to save that
earlier generated image off (push it to my gitlab registry) and refer to it
in the next invocation to actually use it.

**Comment by emersonknapp** [comment]
> Ultimately I would like to be able to save that
earlier generated image off (push it to my gitlab registry) and refer to it
in the next invocation to actually use it.

Makes sense! That should work with this approach - the main point is we need to use a sysroot image that was generated by the tool, rather than some other bare image.

**Comment by kjeremy** [comment]
It sounds like we need another argument that would override the image
generated from the previous stage.

If so could we use one of the existing customization script points to push
the image to a registry or would the program need to be modified to do that
as well?

**Comment by emersonknapp** [comment]
> If so could we use one of the existing customization script points to push
the image to a registry or would the program need to be modified to do that
as well?

There's not a good way to hook this in as-is, since the customization scripts run inside a container, rather than on the host.

High level, what could be done is
* Run with only the `sysroot` step (with an added custom tag option?)
* Upload that tag to a registry
* Run the tool again, starting at `build` step

**Comment by MichaelOrlov** [comment]
- Closing this PR as stale and wouldn't be merged since we are going to archive target repo.
Feel free to reopen if you think will be able to make it ready to be merged in one week time frame.

**Pull request closed without merging**
