### PR TITLE
Updates to follow the updated rep 2000

### PR DESCRIPTION
**Pull request by MichaelOrlov**
- Duplicate #369 with updates in e2e tests.
Update platform.py and README.md to follow the updated REP-2000 - delete dashing add humble update rolling

Solve this issue
https://github.com/ros-tooling/cross_compile/issues/368#issue-1464483861

Note: I cherry picked original commit and add fixes for e2e tests since original fork doesn't allow to push commits from repo maintainers.

### CODE REVIEW

**Comment by MichaelOrlov** [comment]
@christophebedard @emersonknapp Debian jobs still fails - and I don't know why.
Your help in fixing it will be very appreciated.

**Review by emersonknapp — APPROVED** [review]

**Comment by emersonknapp** [comment]
I see you fixed the Debian builds. Now it just looks like the test names changed, so we will need to change those requirements in the branch protection settings

**Comment by christophebedard** [comment]
> I see you fixed the Debian builds. Now it just looks like the test names changed, so we will need to change those requirements in the branch protection settings

Done.

**Comment by MichaelOrlov** [comment]
Oof, I can't believe that I fixed all failing tests in this repo. It was too many failing jobs rather than just Debian and fixes was not so trivial.

**Pull request merged**
