### PR TITLE
Cross Compile: Sysroot creator script update

### PR DESCRIPTION
**Pull request by piraka9011**
This commit updates the cross compilation (CC) sysroot creator script based on the design requirements defined in this ROS2 [PR](https://github.com/ros2/design/pull/249).
Colcon mixins and unit tests will be merged in a later PR which can be found in [the `colcon-mixins` branch](https://github.com/aws-ros-dev/cross_compile/tree/colcon-mixins) and [`tests` branch](https://github.com/aws-ros-dev/cross_compile/tree/tests) respectively.

The script uses a base Docker image to cross compile ROS2 packages across different architectures based on the arguments provided to it. Documentation on how to use is provided.

The script was tested on MacOS Mojave (10.14), Ubuntu Bionic (18.04) for x86 and aarch64, as well as Ubuntu Xenial (16.04).

Edit:
Requesting review from @filiperinaldi @christianrauch

### CODE REVIEW

**Comment by alsora** [comment]
Hi @piraka9011 

As I was mentioning to your colleagues via email, I have some doubts on this cross-compilation framework.

From what I'm seeing, the "cross-compilation" happens inside a Docker image built with qemu. 
We have a base image referred to as `ROS2_BASE_IMG`, and an additional image defined by `Dockerfile_workspace` script.
This has the following issues:
 - The cross-compilation will be much slower than doing it in a X86 environment
 - What if, for a specific architecture, it is not possible to run all the instructions in `Dockerfile_workspace` ?

Moreover, it would be nice to provide instructions for doing the following:
 - Build without having a `ROS2_BASE_IMG`, but rather a sysroot directory
 - Build only a specific package

**Comment by alsora** [comment]
Just some quick replies, then tomorrow I will read the design PR more in details.

---

> I suggest having the platform support builds embedded into docker images instead of on the host. So that you don't need to have the cross compilation resources on your local machine, just a docker dependency.

I agree with this statement, but there are different ways for satisfying it:
 - Use a Docker image for the target architecture, built with qemu, and build ROS2 inside it.
 - Use a Docker image for Ubuntu 18.04 with all the cross-compilation dependencies and cross-compile ROS2 there.

Correct me if I'm wrong, but you did the first. I think that the second implementation would be much better for the reasons mentioned above.

---

> Build without having a `ROS2_BASE_IMG`, but rather a sysroot directory

This does not require to install any dependency on the host system in order to be satisfied.
It may be the case that I do not have a Docker image at hand for my target architecture, but rather I only have the `lib`, `include`, `etc` directories for my target system, downloaded from somewhere.

IMO, the cross-compilation command/script should accept the following arguments:
 - cross-compile --sysroot <NAME_OF_ROS2_BASE_IMG>
 - cross-compile --sysroot <PATH_TO_SYSROOT_DIRECTORY>

**Comment by alsora** [comment]
@piraka9011 have you had a look at the Dockefiles that I'm using in my PR? 
Specifically, the ones contained in the `docker_environments` directory.
They are used exactly for this purpose. 

There is a dockerfile_base that installs general ROS2 dependencies in a x86 Ubuntu 18.04 environment. 
Then you have a different file for each architecture that installs the compiler. 

Do you. Think that we could integrate them into this PR?

**Comment by emersonknapp** [comment]
@piraka9011 @thomas-moulard how are we doing on this tool, are we ready to move forward with this first version or does it need reworking?

**Comment by thomas-moulard** [comment]
We agreed to basically merge our fork in this repo, as long as 1/ the current state of master is tagged so that it remains accessible, and 2/ we update the doc as needed.
My suggestion is to close this PR, prepare a doc PR update, and just merged directly back our fork into master after tagging the current HEAD.

**Comment by piraka9011** [comment]
ditto Thomas 
+
I believe we just need to x2 check the requirements in the `setup.py` to make sure it can be bloom released/installed as a standalone package.

**Comment by prajakta-gokhale** [comment]
Closing in favor of https://github.com/ros-tooling/cross_compile/pull/22

**Pull request closed without merging**
