### PR TITLE
Raspbian Stretch support

### PR DESCRIPTION
**Pull request by christianrauch**
This PR adds a docker file for Raspbian.

At the moment, I cannot successfully build ROS2 with this image since the library `libPocoFoundation.so.50`, which is installed by `poco_vendor`, cannot be found.
This issue does not appear on Ubuntu, since this library is provided by package `libpocofoundation50`.

# Build

The instructions are adapted from https://index.ros.org/doc/ros2/Tutorials/Cross-compilation/.

1. create rootfs:
```bash
docker build -t raspbian_ros2:latest -f ros2_ws/src/ros2/cross_compile/sysroot/Dockerfile_raspbian_arm .
```
```bash
docker create --name arm_sysroot raspbian_ros2
docker container export -o sysroot_docker.tar arm_sysroot
docker rm arm_sysroot
mkdir sysroot_docker
tar -C sysroot_docker -xf sysroot_docker.tar lib usr opt etc
```

2. build:
```bash
export TARGET_ARCH=armhf
export TARGET_TRIPLE=arm-linux-gnueabihf
export CC=/usr/bin/$TARGET_TRIPLE-gcc
export CXX=/usr/bin/$TARGET_TRIPLE-g++
export CROSS_COMPILE=/usr/bin/$TARGET_TRIPLE-
export SYSROOT=~/ros2_rpi/sysroot_docker
export ROS2_INSTALL_PATH=~/ros2_rpi/ros2_ws/install
export PYTHON_SOABI=cpython-36m-$TARGET_TRIPLE
```

```bash
colcon build --merge-install \
    --cmake-force-configure \
    --cmake-args \
        -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
        -DCMAKE_TOOLCHAIN_FILE="$(pwd)/src/ros2/cross_compile/cmake-toolchains/generic_linux.cmake"
```

# Unresolved issues

The build fails (at package `test_msgs`) because the poco library cannot be found:
```
 warning: libPocoFoundation.so.50, needed by ~/ros2_rpi/ros2_ws/install/lib/librosidl_typesupport_cpp.so, not found (try using -rpath or -rpath-link)
```
even though it's located in the `install` space:
```
file install/lib/libPocoFoundation.so.50
install/lib/libPocoFoundation.so.50: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=b79d43aa8df0349394cbf54c0b2fd18bdaf0af0a, with debug_info, not stripped
```
The issue still persists after setting the rpath via ``-DCMAKE_BUILD_RPATH="`pwd`/install/lib/"``.

Did anyone encounter the same issue?

### CODE REVIEW

**Comment by lmayencourt** [comment]
Hi @christianrauch !
Poco is still an issue for the cross-compilation of ROS2. Your issue may be related to https://github.com/ros2/cross_compile/issues/11

Have you tried with our current workaround, which create a symlink to poco and zlib ?
```
mkdir -p /usr/lib/$TARGET_TRIPLE
ln -s `pwd`/sysroot_docker/lib/$TARGET_TRIPLE/libz.so.1 /usr/lib/$TARGET_TRIPLE/libz.so
ln -s `pwd`/sysroot_docker/lib/$TARGET_TRIPLE/libpcre.so.3 /usr/lib/$TARGET_TRIPLE/libpcre.so
```

**Comment by nuclearsandwich** [comment]
cc @emersonknapp as we were discussing raspbian cross-compilation recently.

**Comment by christianrauch** [comment]
@lmayencourt I think my issue is independent of this since the library was successfully built and installed. The issue that remains is that it cannot be found in consecutive builds.

I also tried to set the rpath via:
```
-DCMAKE_BUILD_RPATH="`pwd`/build/poco_vendor/poco_external_project_install/lib/;`pwd`/build/libyaml_vendor/libyaml_install/lib/"
```
as proposed in https://github.com/ros2-for-arm/ros2/wiki/ROS2-on-arm-architecture#trigger-a-build, but with no avail.

**Comment by alsora** [comment]
Hi, we (iRobot) just released some Docker based cross-compilation tools for raspbian.
You can find them here
https://github.com/irobot-ros/ros2-performance/tree/master/cross-compiling

That's one of the problems that was bugging me the most, I solved it in the following way

> in the .toolchain.cmake file that you are using, add to the CMAKE_C_FLAGS and CMAKE_CXX_FLAGS a linker path to the current workspace library directory, for example -Wl,-rpath-link=/root/ws/install/lib

More details in the [troubleshooting section](https://github.com/irobot-ros/ros2-performance/blob/master/cross-compiling/troubleshooting.md#linker-missing-libpocofoundation-and-or-libyaml).

I hope this fixes the problem for you, as far as I have seen this issue depends on the compiler that you are using.

Moreover, if there is anything else, I'm willing to contribute to help merging our cross-compilation tools into this repo.

**Comment by christianrauch** [comment]
@alsora I am still hitting the same issue:
``
/usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/bin/ld: warning: libPocoFoundation.so.50, needed by <workspace>/install/lib/librmw_implementation.so, not found (try using -rpath or -rpath-link)
``
with a toolchain file that sets the flags to `"-Wl,-rpath-link=$ENV{ROS2_INSTALL_PATH}/lib"`.

It would be useful if you could merge your Docker and toolchain file into this repo, either via this or a new PR.

**Comment by alsora** [comment]
I opened a new PR https://github.com/ros2/cross_compile/pull/15
It includes this one and fixes the problem using a different compiler

**Comment by christianrauch** [comment]
I managed to cross-compile and work around the POCO linking issue by building the individual failing packages using `--packages-select`. I.e. you `colcon build` the whole workspace according to documentation and when the build fails for a certain package `A` because of POCO, you build this package via `colcon build --packages-select A` and then repeat `colcon build` to continue.

**Comment by alsora** [comment]
Mmm it looks like a very error-prone solution.
Are you able to distinguish if package `A` really fails due to POCO or due something else?

In any case, if using `package-select` works, it should work also if you do it as first command and then you `colon build` the whole workspace (instead of waiting for a failure). 
This looks slightly better to me.

**Comment by alsora** [comment]
@christianrauch this solutions looks quite error-prone...
Are you able to determine whether `package_A` fails due to POCO or due to something else?

However, it's interesting to understand the cause of our problems.
Does your new solution work because you are building multiple times or because you are using `package-select`?

In the first case, a better approach could be to build POCO alone first of all, using `colcon build --package-select poco_vendor`, and then all the workspace with `colcon build`.
In the second case, we should open a ticket on the `colcon` repository for that...

**Comment by christianrauch** [comment]
The build issues are still caused by POCO. I was able to build eventually by building the failing packages with `package-select` and then continue building all until the next package failed.
E.g. build all -> pkg A fails -> build A -> build all -> pkg B fails -> build B -> build all -> ...
If you build all multiple times does not change the order in which packages are built. E.g. the failing package will always fail at the same point.
As a note, this might only work with the GCC version 6 cross-compiler suite.

**Comment by alsora** [comment]
Mmm ok, that looks strange.
A last thing that comes to my mind is that there could be a difference in how libraries and headers are loaded depending on if the package providing them is included in this execution of `colcon build` or not.

In the case doing the following may work...

`colcon build --package-select poco_vendor`
`touch src/ros2/poco_vendor/COLCON_IGNORE`
`colcon build`

**Comment by pokitoz** [comment]
Do you have any update on this PR? It looks like https://github.com/ros2/cross_compile/pull/18 is also doing the same thing.

Could this one be closed ?

**Comment by christianrauch** [comment]
Yes, #18 works for Raspbian on Raspberry Pi 2 and later. I haven't managed to cross-compile for the Pi 1 with either of these PRs. If #18 is going to get merged, I am happy to have this closed.

**Comment by emersonknapp** [comment]
Closing this PR as out of date. Checking on raspbian support in the new tool would be a welcome contribution.

**Pull request closed without merging**
