### PR TITLE
Quick fix for issue #360

### PR DESCRIPTION
**Pull request by Le5tes**
This fixes the bug that I had: https://github.com/ros-tooling/cross_compile/issues/360

Not sure if anyone else is having this issue, so if not feel free to ignore!

### CODE REVIEW

**Comment by MichaelOrlov** [comment]
@Le5tes I don't mind about this fix. I am only worry about failing tests on CI.
Could you please try to fix warnings reported from linters?
```
=================================== FAILURES ===================================
_________________________________ test_flake8 __________________________________
    @pytest.mark.flake8
    @pytest.mark.linter
    def test_flake8():
        logging.getLogger('flake8').setLevel(logging.INFO)
        rc = main(argv=[])
>       assert rc == 0, 'Found errors'
E       AssertionError: Found errors
E       assert 1 == 0
E         +1
E         -0
test/test_flake8.py:26: AssertionError
----------------------------- Captured stdout call -----------------------------
./ros_cross_compile/docker_client.py:72:26: Q000 Double quotes found but single quotes preferred
            network_mode="host"
                         ^
1     Q000 Double quotes found but single quotes preferred
```

**Comment by christophebedard** [comment]
Looks okay to me. Could you sign off your commit(s) so that they pass the DCO check? https://github.com/ros-tooling/cross_compile/pull/361/checks?check_run_id=7336140466

Not sure what's going on with the shellcheck linter failure. The other failures are in the nightly job as well: https://github.com/ros-tooling/cross_compile/actions/runs/2665228259

**Comment by Le5tes** [comment]
I signed off the commits. I'll have a look into the test failures a bit over the weekend.

**Comment by MichaelOrlov** [comment]
@Le5tes Could you please address linter  errors in you PR?
We are going to archive entire repo very soon and this is last chance to get it throw.

**Review by MichaelOrlov — APPROVED** [review]

**Review by emersonknapp — APPROVED** [review]

**Comment by TSC21** [comment]
> @Le5tes Could you please address linter errors in you PR? We are going to archive entire repo very soon and this is last chance to get it throw.

@MichaelOrlov can you please clarify what this means? Are you guys stopping supporting the tool?

**Comment by MichaelOrlov** [comment]
@Le5tes Yes we are going to archive this repo and deprecate. 
The rational for that:
1. There are no volunteers to support it and I don't have enough knowledge and time to support it as well.
2. We have made a post on Discourse about it in July https://discourse.ros.org/t/call-for-help-maintainership-of-the-ros-cross-compile-tool/26511
3. Community mostly expressed opinion that it's outdated and inefficient. It was recommended to use the native cross-compilation instead of QUEMU

**Pull request merged**
